trigger:
  branches:
    include:
      - test

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: download_and_copy
  steps:
  - task: DownloadSecureFile@1
    name: download
    displayName: 'Download Secure File'
    inputs:
      secureFile: 'File'

  - script: |
      cat $(download.secureFilePath)
    displayName: 'Copy file to workspace directory'

- job: set_ssh_public_key
  displayName: 'Set SSH_PUBLIC_KEY variable'
  steps:
  - script: |
      echo '##vso[task.setvariable variable=SSH_PUBLIC_KEY]$(cat /home/roshnipatel/.ssh/id_rsa.pub)'
    displayName: 'Set SSH_PUBLIC_KEY variable'

- job: terraform_approval
  displayName: "Terraform Approval"
  dependsOn: set_ssh_public_key
  steps:
    - script: 
        echo "Terraform Approval Job"
      displayName: 'Terraform Approval'
      condition: succeededOrFailed()

    - script: |
        ls -la
        pwd
        cd $(Build.SourcesDirectory)
        pwd
        cd rose
        echo "ssh_public_key = \"$${env:SSH_PUBLIC_KEY}\"" > terraform.auto.tfvars
        terraform init
        terraform validate
        az login 
        terraform plan -var-file=terraform.auto.tfvars
      displayName: 'Terraform Plan'
