trigger:
  branches:
    include:
      - test

pool:
  vmImage: 'ubuntu-latest'

  # Add additional steps based on your requirements
 - task: DownloadSecureFile@1
            name: download
            inputs:
              secureFile: 'File'
          - script: |
              cat $(download.secureFilePath) | 
            displayName: 'Copy file to workspace directory'