trigger:
  branches:
    include:
      - test

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: download_and_copy
  steps:
  - task: DownloadSecureFile@1
    name: download
    displayName: 'Download Secure File'
    inputs:
      secureFile: 'File'

  - script: |
      cat $(download.secureFilePath)
    displayName: 'Copy file to workspace directory'

- job: terraform_approval
  displayName: "Terraform Approval"
  steps:
    - script: 
        echo "Terraform Approval Job"
      displayName: 'Terraform Approval'
      condition: succeededOrFailed()

- job: manual_approval
  displayName: "Manual Approval"
  dependsOn: terraform_approval
  pool:
    vmImage: 'ubuntu-latest' 
  steps:
    - script: 
        echo "Manual Approval Job"
      displayName: 'Manual Approval'

    - script: |
        ls -la
        pwd
        cd $(Build.SourcesDirectory)
        pwd
        cd rose  # Assuming the Terraform files are in the 'rose' directory
        pwd
        terraform init
      displayName: 'Terraform Init'

    - script: |
        cd rose
        terraform validate
      displayName: 'Terraform Validate'

    - script: |
        az login 
      displayName: 'Azure Login'  

    - script: |
        cd rose
        terraform plan 
      displayName: 'Terraform Plan'

- job: manual_intervention
  displayName: 'Manual Approval Intervention'
  dependsOn: manual_approval
  pool: server
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 5
    inputs:
      instructions: 'Please review and manually approve the Terraform changes.'

- job: apply_changes
  displayName: 'Apply Terraform Changes'
  dependsOn: manual_intervention
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      cd $(Build.SourcesDirectory)/rose
      terraform init
      az login 
      terraform apply -auto-approve
    displayName: 'Apply Terraform Changes'
