trigger:
  branches:
    include:
      - test

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadSecureFile@1
    name: 'downloadSSHKey'
    displayName: 'Download Secure File'
    inputs:
      secureFile: 'file' # Replace with your secure file name

  # Add more steps as needed:
  - script: |
      cd "$(Agent.TempDirectory)/_work/_temp/$(downloadSSHKey.secureFileFileName)"
      # Now, you can use the secure file as needed
    displayName: 'Run Script'

  # Add additional steps based on your requirements
